In [1]:
import pandas as pd
import json

In [2]:
df = pd.read_csv('movie_to_cluster.csv')
df.head()

    movie_id  cluster
0  tt0035423        8
1  tt0088751       12
2  tt0096056        6
3  tt0113092        3
4  tt0116391        3

In [3]:
movie_genre_map = {}

with open('imdb_movies_2000to2022.prolific.json') as f:
    for line in f:
        movie = json.loads(line)
        movie_genre_map[movie['imdb_id']] = movie['genres']

In [4]:
# Combine df and map based on id into a new dataframe where df movie_id = map imdb_id, make genres as comma separated string

df['genres'] = df['movie_id'].map(movie_genre_map)
df['genres'] = df['genres'].apply(lambda x: ', '.join(x))

df.head()

    movie_id  cluster                    genres
0  tt0035423        8  Comedy, Fantasy, Romance
1  tt0088751       12    Comedy, Horror, Sci-Fi
2  tt0096056        6                     Drama
3  tt0113092        3  Action, Adventure, Drama
4  tt0116391        3      Action, Crime, Drama

In [6]:
# Set your target genre as "Sci-Fi"
target_genre = "Sci-Fi"

total_movies = len(df)
print(total_movies)

sci_fi_movies = len(df[df['genres'].str.contains(target_genre)])
print(sci_fi_movies)

clusters = df['cluster'].unique()
print(clusters)

20620
1055
[ 8 12  6  3 14  9  1 13  0  2 15  7  4 11  5 10]

In [8]:
# Use a for loop to iterate through the clusters. For each one, calculate the probability that a new movie will 
# fit in that cluster given that it is a Sci-Fi movie. In other words calculate P(Cluster | Sci-Fi)

for cluster in clusters:
    cluster_movies = len(df[df['cluster'] == cluster])
    sci_fi_in_cluster = len(df[(df['cluster'] == cluster) & (df['genres'].str.contains(target_genre))])
    prob = sci_fi_in_cluster / sci_fi_movies
    print(f"Probability of {cluster} given Sci-Fi: {prob}")

Probability of 8 given Sci-Fi: 0.008530805687203791
Probability of 12 given Sci-Fi: 0.18862559241706162
Probability of 6 given Sci-Fi: 0.061611374407582936
Probability of 3 given Sci-Fi: 0.024644549763033177
Probability of 14 given Sci-Fi: 0.03033175355450237
Probability of 9 given Sci-Fi: 0.021800947867298578
Probability of 1 given Sci-Fi: 0.04075829383886256
Probability of 13 given Sci-Fi: 0.013270142180094787
Probability of 0 given Sci-Fi: 0.1734597156398104
Probability of 2 given Sci-Fi: 0.2037914691943128
Probability of 15 given Sci-Fi: 0.13175355450236967
Probability of 7 given Sci-Fi: 0.0
Probability of 4 given Sci-Fi: 0.05308056872037915
Probability of 11 given Sci-Fi: 0.04739336492890995
Probability of 5 given Sci-Fi: 0.0
Probability of 10 given Sci-Fi: 0.0009478672985781991

In [18]:
df.head()

    movie_id  cluster                    genres
0  tt0035423        8  Comedy, Fantasy, Romance
1  tt0088751       12    Comedy, Horror, Sci-Fi
2  tt0096056        6                     Drama
3  tt0113092        3  Action, Adventure, Drama
4  tt0116391        3      Action, Crime, Drama

In [ ]:
#3. Set your target cluster as "Cluster0"

target_cluster = 0

#4. Use a for loop to iterate through the genres. For each one,  calculate P(Genre | Cluster0) 
# Genres cintains list of genres comma separated and I only look for individual genres

for genre in df['genres'].str.split(', ').explode().unique():
    if genre.strip() == "":
        continue
    genre_movies = len(df[(df['genres'].str.contains(genre)) & (df['cluster'] == target_cluster)])
    cluster_movies = len(df[df['cluster'] == target_cluster])
    if cluster_movies == 0:
        prob = 0
    else:
        prob = genre_movies / cluster_movies
    print(f"Probability of {genre} given {target_cluster}: {prob}")

Probability of Comedy given 0: 0.6580561834032935
Probability of Fantasy given 0: 0.06748466257668712
Probability of Romance given 0: 0.0
Probability of Horror given 0: 0.0
Probability of Sci-Fi given 0: 0.05908944139489829
Probability of Drama given 0: 0.0
Probability of Action given 0: 0.0
Probability of Adventure given 0: 0.15305134000645787
Probability of Crime given 0: 0.08459799806264126
Probability of Mystery given 0: 0.01517597675169519
Probability of Thriller given 0: 0.00032289312237649337
Probability of Animation given 0: 0.1504681950274459
Probability of Family given 0: 0.1611236680658702
Probability of Biography given 0: 0.00871811430416532
Probability of Sport given 0: 0.044559250887956085
Probability of Music given 0: 0.03196641911527284
Probability of Western given 0: 0.03132063287051986
Probability of War given 0: 0.009041007426541814
Probability of History given 0: 0.005489183080400388
Probability of Musical given 0: 0.018727801097836616
Probability of Documentary given 0: 0.00032289312237649337
Probability of Short given 0: 0.0
Probability of News given 0: 0.0
Probability of Reality-TV given 0: 0.0006457862447529867